### ISSUE TITLE
Errors in  tools/cityscapes/make_cityscapes_tfrecords.py

### ISSUE THREAD

**Issue by yakubota** [MaybeShewill-CV/bisenetv2-tensorflow#16]
When I use this command to test, I got error:
The following error occurred. Please point out what needs to be fixed.

I think the problem is where to place the train.txt. I put it in several directories, but I don't know the right answer, so I'm not sure where to put the file. Please tell me if I should.

python python tools/cityscapes/make_cityscapes_tfrecords.py

Error:
[Errno 2] No such file or directory: '/data/example_dataset/cityscapes/image_file_index/train.txt'
Traceback (most recent call last):
  File "tools/cityscapes/make_cityscapes_tfrecords.py", line 32, in <module>
    generate_tfrecords()
  File "tools/cityscapes/make_cityscapes_tfrecords.py", line 22, in generate_tfrecords
    io = cityscapes_tf_io.CityScapesTfIO()
  File "C:\Users\students\Desktop\rakuseki\seg\bisenetv2-tensorflow-master\bisenetv2-tensorflow-master\tools\cityscapes\data_provider\cityscapes\cityscapes_tf_io.py", line 279, in __init__
    self._writer = _CityScapesTfWriter()
  File "C:\Users\students\Desktop\rakuseki\seg\bisenetv2-tensorflow-master\bisenetv2-tensorflow-master\tools\cityscapes\data_provider\cityscapes\cityscapes_tf_io.py", line 68, in __init__
    self._load_train_val_image_index()
  File "C:\Users\students\Desktop\rakuseki\seg\bisenetv2-tensorflow-master\bisenetv2-tensorflow-master\tools\cityscapes\data_provider\cityscapes\cityscapes_tf_io.py", line 90, in _load_train_val_image_index
    raise err
  File "C:\Users\students\Desktop\rakuseki\seg\bisenetv2-tensorflow-master\bisenetv2-tensorflow-master\tools\cityscapes\data_provider\cityscapes\cityscapes_tf_io.py", line 79, in _load_train_val_image_index
    with open(self._train_image_index_file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/data/example_dataset/cityscapes/image_file_index/train.txt'

**Comment by MaybeShewill-CV** [comment]
@yakubota Check this file and make sure you have the right file path here. https://github.com/MaybeShewill-CV/bisenetv2-tensorflow/blob/ea07cc35d33989417236394c442ca42f3f8db342/config/cityscapes/cityscapes_bisenetv2.yaml#L25-L36

**Comment by yakubota** [comment]
I checked "bisenetv2.yaml". What folder is that relative path based on?

**Comment by MaybeShewill-CV** [comment]
@yakubota You may put absolute path here:)

**Comment by yakubota** [comment]
When I add the path to the base folder path, I get a text file,  "train.txt". Specifically, I want to know which folder I should put the  "train.txt" in based on this "bisenetv2.yaml" that you presented. Let me know if that's okay.

add path: "/PATH/IMAGE_SCENE_SEGMENTATION/CITYSPACES/image_file_index/train.txt"

"bisenetv2.yaml" file of mine is the same as the one I downloaded.

![image](https://user-images.githubusercontent.com/64525148/86508819-ff9c8c00-be1d-11ea-9007-8d99efdc4a71.png)

**Comment by MaybeShewill-CV** [comment]
@yakubota You can put "train.txt" to anywhere you like as if the file path was correctly written in the yams file:)

**Comment by MaybeShewill-CV** [comment]
@yakubota Eg. If you put train.txt file in D:\\train.txt then you should write D:\\train.txt to yaml file:)

**Comment by yakubota** [comment]
Thank you. It's done! I'm sorry for the trouble I've caused you.

**Comment by MaybeShewill-CV** [comment]
@yakubota Welcome:)
