### ISSUE TITLE
你好 我无法解决这个问题

### ISSUE THREAD

**Issue by cnu-Dawn** [MaybeShewill-CV/bisenetv2-tensorflow#56]
WARNING:tensorflow:From tools/cityscapes/test_bisenetv2_cityscapes.py:120: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/hdp123/bisenetv2-tensorflow/bisenet_model/bisenet_v2.py:1187: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/hdp123/bisenetv2-tensorflow/bisenet_model/cnn_basenet.py:71: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/hdp123/bisenetv2-tensorflow/bisenet_model/cnn_basenet.py:411: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
WARNING:tensorflow:From /home/hdp123/anaconda3/envs/Unet/lib/python3.7/site-packages/tensorflow_core/python/layers/normalization.py:327: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/hdp123/bisenetv2-tensorflow/bisenet_model/cnn_basenet.py:222: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /home/hdp123/bisenetv2-tensorflow/bisenet_model/cnn_basenet.py:246: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

WARNING:tensorflow:From /home/hdp123/bisenetv2-tensorflow/bisenet_model/bisenet_v2.py:585: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

WARNING:tensorflow:From tools/cityscapes/test_bisenetv2_cityscapes.py:133: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From tools/cityscapes/test_bisenetv2_cityscapes.py:137: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2024-03-12 11:51:00.323528: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2024-03-12 11:51:00.346827: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3110400000 Hz
2024-03-12 11:51:00.347344: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5ee58a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-03-12 11:51:00.347364: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2024-03-12 11:51:00.348556: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2024-03-12 11:51:00.467029: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-03-12 11:51:00.467490: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5dc8ca0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-03-12 11:51:00.467508: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 3060 Laptop GPU, Compute Capability 8.6
2024-03-12 11:51:00.467623: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-03-12 11:51:00.467908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce RTX 3060 Laptop GPU major: 8 minor: 6 memoryClockRate(GHz): 1.425
pciBusID: 0000:01:00.0
2024-03-12 11:51:00.467997: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hdp123/anaconda3/envs/Unet/lib/python3.7/site-packages/cv2/../../lib64:/opt/ros/melodic/lib::/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu
2024-03-12 11:51:00.468042: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hdp123/anaconda3/envs/Unet/lib/python3.7/site-packages/cv2/../../lib64:/opt/ros/melodic/lib::/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu
2024-03-12 11:51:00.468079: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hdp123/anaconda3/envs/Unet/lib/python3.7/site-packages/cv2/../../lib64:/opt/ros/melodic/lib::/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu
2024-03-12 11:51:00.468114: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hdp123/anaconda3/envs/Unet/lib/python3.7/site-packages/cv2/../../lib64:/opt/ros/melodic/lib::/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu
2024-03-12 11:51:00.468147: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hdp123/anaconda3/envs/Unet/lib/python3.7/site-packages/cv2/../../lib64:/opt/ros/melodic/lib::/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu
2024-03-12 11:51:00.468181: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hdp123/anaconda3/envs/Unet/lib/python3.7/site-packages/cv2/../../lib64:/opt/ros/melodic/lib::/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu
2024-03-12 11:51:00.468216: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hdp123/anaconda3/envs/Unet/lib/python3.7/site-packages/cv2/../../lib64:/opt/ros/melodic/lib::/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu
2024-03-12 11:51:00.468220: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-03-12 11:51:00.468230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-03-12 11:51:00.468234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2024-03-12 11:51:00.468237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
WARNING:tensorflow:From tools/cityscapes/test_bisenetv2_cityscapes.py:146: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

[ WARN:0@1.944] global loadsave.cpp:248 findDecoder imread_(''): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "tools/cityscapes/test_bisenetv2_cityscapes.py", line 193, in <module>
    weights_path=args.weights_path
  File "tools/cityscapes/test_bisenetv2_cityscapes.py", line 150, in test_bisenet_cityspaces
    preprocessed_image = preprocess_image(src_image, input_tensor_size)
  File "tools/cityscapes/test_bisenetv2_cityscapes.py", line 72, in preprocess_image
    output_image = src_image[:, :, (2, 1, 0)]
TypeError: 'NoneType' object is not subscriptable
这是什么原因

**Comment by MaybeShewill-CV** [comment]
@LoveMYChen debug看下图像路径是否传输正确 如果是相对路径 看下命令启动的位置是否对应这个相对路径:)
